-- AniArix anime identity and metadata foundation.
--
-- This migration is intentionally additive and idempotent. It does not
-- modify or delete existing watch_history rows, profiles, auth data, or
-- AniList sync-cache data.

begin;

-- Keep the existing AniList identifier for compatibility, but allow MAL-only
-- catalog entries in the next application phase.
alter table public.watch_history
  alter column anilist_id drop not null;

alter table public.watch_history
  add column if not exists mal_id integer;

create index if not exists watch_history_anilist_id_idx
  on public.watch_history (anilist_id)
  where anilist_id is not null;

create index if not exists watch_history_mal_id_idx
  on public.watch_history (mal_id)
  where mal_id is not null;

-- Global (not user-owned) source-identity and normalized metadata store.
-- At least one upstream identity is mandatory; both can be present when the
-- AniList-to-MAL mapping is known.
create table if not exists public.anime_catalog (
  id bigint generated by default as identity primary key,
  anilist_id integer,
  mal_id integer,
  title_english text,
  title_romaji text,
  title_native text,
  poster text,
  banner text,
  description text,
  format text,
  status text,
  episodes integer,
  duration integer,
  season text,
  season_year integer,
  genres jsonb,
  metadata_source text,
  last_synced_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The table may already have been created outside this repository. Add every
-- required metadata column without overwriting values or changing nullability
-- of existing data.
alter table public.anime_catalog
  add column if not exists anilist_id integer,
  add column if not exists mal_id integer,
  add column if not exists title_english text,
  add column if not exists title_romaji text,
  add column if not exists title_native text,
  add column if not exists poster text,
  add column if not exists banner text,
  add column if not exists description text,
  add column if not exists format text,
  add column if not exists status text,
  add column if not exists episodes integer,
  add column if not exists duration integer,
  add column if not exists season text,
  add column if not exists season_year integer,
  add column if not exists genres jsonb,
  add column if not exists metadata_source text,
  add column if not exists last_synced_at timestamptz,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

-- A catalog table that predates this migration may have a bigint primary key
-- without a generated value. Add an identity sequence without touching IDs
-- already present, so trusted server-side inserts can create new mappings.
do $$
declare
  identity_kind "char";
  column_default text;
  sequence_name text;
  max_id bigint;
begin
  select a.attidentity, pg_get_expr(d.adbin, d.adrelid)
    into identity_kind, column_default
  from pg_attribute a
  left join pg_attrdef d
    on d.adrelid = a.attrelid
    and d.adnum = a.attnum
  where a.attrelid = 'public.anime_catalog'::regclass
    and a.attname = 'id'
    and not a.attisdropped;

  if coalesce(identity_kind, '') = '' and column_default is null then
    alter table public.anime_catalog
      alter column id add generated by default as identity;
  end if;

  select pg_get_serial_sequence('public.anime_catalog', 'id') into sequence_name;
  if sequence_name is not null then
    select max(id) into max_id from public.anime_catalog;
    if max_id is null then
      perform setval(sequence_name, 1, false);
    else
      perform setval(sequence_name, max_id, true);
    end if;
  end if;
end
$$;

-- Partial unique indexes permit multiple NULL values while making each known
-- external ID globally unique.
create unique index if not exists anime_catalog_anilist_id_unique_idx
  on public.anime_catalog (anilist_id)
  where anilist_id is not null;

create unique index if not exists anime_catalog_mal_id_unique_idx
  on public.anime_catalog (mal_id)
  where mal_id is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'anime_catalog_requires_external_id'
      and conrelid = 'public.anime_catalog'::regclass
  ) then
    alter table public.anime_catalog
      add constraint anime_catalog_requires_external_id
      check (anilist_id is not null or mal_id is not null);
  end if;
end
$$;

-- Catalog rows are public read-only metadata. RLS remains enabled and there
-- are no anon/authenticated write grants or write policies. service_role
-- server-side code bypasses RLS for trusted writes.
alter table public.anime_catalog enable row level security;

grant select on table public.anime_catalog to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on table public.anime_catalog from anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'anime_catalog'
      and policyname = 'anime_catalog_public_select'
  ) then
    create policy anime_catalog_public_select
      on public.anime_catalog
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

commit;
